# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7a022df5624e244ccd7d9d598c5517dda1a6162bd095eb952fc85782ad765b4839332241317d1aa6b8cb23e528caedd33b63c7ee725eb30b508988d6e290da4

test:
  secret_key_base: 95809db21c3524e3124dd9a7a806faadaaded16728a912a72369e225b437a692287916ef52aba7762f4cbead9f593635db2921b070a212d46c9c23651d13af25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
